import type { Portal } from '@app-types/index';

export const PORTAL_CONFIGS: Portal[] = [
  {
    id: 'admin',
    name: 'Enterprise Administration',
    description: 'System administration and governance',
    icon: 'SettingOutlined',
    route: '/portals/admin',
    allowedRoles: ['SystemAdministrator', 'ITSecurityAdmin', 'CoreBankingAdmin'],
    color: '#722ed1',
  },
  {
    id: 'executive',
    name: 'Executive & Board',
    description: 'Strategic dashboards and oversight',
    icon: 'DashboardOutlined',
    route: '/portals/executive',
    allowedRoles: ['CEO', 'CFO', 'CRO', 'COO', 'BoardMember'],
    color: '#f5222d',
  },
  {
    id: 'branch-manager',
    name: 'Branch Manager',
    description: 'Branch performance and operations',
    icon: 'BankOutlined',
    route: '/portals/branch-manager',
    allowedRoles: ['BranchManager', 'RegionalManager'],
    color: '#1890ff',
  },
  {
    id: 'branch-operations',
    name: 'Branch Operations',
    description: 'Vault, cash, and EOD/BOD operations',
    icon: 'SafetyOutlined',
    route: '/portals/branch-operations',
    allowedRoles: ['VaultOfficer', 'OperationsOfficer', 'BranchManager'],
    color: '#13c2c2',
  },
  {
    id: 'teller',
    name: 'Teller Portal',
    description: 'Frontline banking operations',
    icon: 'UserOutlined',
    route: '/portals/teller',
    allowedRoles: ['Teller', 'Supervisor', 'BranchManager'],
    color: '#52c41a',
  },
  {
    id: 'supervisor',
    name: 'Supervisor Portal',
    description: 'Team oversight and approvals',
    icon: 'TeamOutlined',
    route: '/portals/supervisor',
    allowedRoles: ['Supervisor', 'BranchManager'],
    color: '#fa8c16',
  },
  {
    id: 'compliance',
    name: 'Compliance & Risk',
    description: 'AML, fraud, and risk management',
    icon: 'AlertOutlined',
    route: '/portals/compliance',
    allowedRoles: ['AMLOfficer', 'FraudAnalyst', 'RiskOfficer', 'ComplianceManager'],
    color: '#eb2f96',
  },
  {
    id: 'treasury',
    name: 'Treasury & Markets',
    description: 'FX, MM, and liquidity operations',
    icon: 'DollarOutlined',
    route: '/portals/treasury',
    allowedRoles: ['TreasuryDealer', 'LiquidityManager'],
    color: '#2f54eb',
  },
  {
    id: 'trade-finance',
    name: 'Trade Finance',
    description: 'LCs, guarantees, and collections',
    icon: 'ContainerOutlined',
    route: '/portals/trade-finance',
    allowedRoles: ['TradeFinanceOfficer', 'CorporateBankingOfficer'],
    color: '#a0d911',
  },
  {
    id: 'product-gl',
    name: 'Product & GL',
    description: 'Product lifecycle and GL management',
    icon: 'AppstoreOutlined',
    route: '/portals/product-gl',
    allowedRoles: ['ProductManager', 'FinanceController'],
    color: '#faad14',
  },
  {
    id: 'payments',
    name: 'Payments & Clearing',
    description: 'Payment processing and clearing',
    icon: 'SwapOutlined',
    route: '/portals/payments',
    allowedRoles: ['PaymentsOfficer', 'ClearingOfficer'],
    color: '#13c2c2',
  },
  {
    id: 'customer',
    name: 'Customer Digital',
    description: 'Customer self-service banking',
    icon: 'MobileOutlined',
    route: '/portals/customer',
    allowedRoles: ['RetailCustomer', 'SMECustomer'],
    color: '#52c41a',
  },
  {
    id: 'staff',
    name: 'Staff Self-Service',
    description: 'HR, leave, payroll, and training',
    icon: 'IdcardOutlined',
    route: '/portals/staff',
    allowedRoles: [
      'Teller',
      'Supervisor',
      'BranchManager',
      'OperationsOfficer',
      'VaultOfficer',
      'AMLOfficer',
      'FraudAnalyst',
      'RiskOfficer',
      'ComplianceManager',
      'TreasuryDealer',
      'LiquidityManager',
      'TradeFinanceOfficer',
      'CorporateBankingOfficer',
      'ProductManager',
      'FinanceController',
      'PaymentsOfficer',
      'ClearingOfficer',
    ],
    color: '#722ed1',
  },
  {
    id: 'workflow',
    name: 'Workflow & Task',
    description: 'Approval routing and task management',
    icon: 'DeploymentUnitOutlined',
    route: '/portals/workflow',
    allowedRoles: [
      'SystemAdministrator',
      'CoreBankingAdmin',
      'Supervisor',
      'BranchManager',
      'ComplianceManager',
    ],
    color: '#f759ab',
  },
];
