using Wekeza.Core.Domain.Aggregates;
using Wekeza.Core.Domain.Common;
using Wekeza.Core.Domain.Enums;

namespace Wekeza.Core.Domain.Interfaces;

/// <summary>
/// Report Repository Interface - Data access for Report aggregate
/// Supports financial, regulatory, operational, and analytical reports
/// Industry Standard: Repository pattern for enterprise reporting systems
/// </summary>
public interface IReportRepository : IRepository<Report>
{
    // ============================================================================
    // BASIC CRUD OPERATIONS
    // ============================================================================
    
    /// <summary>
    /// Get report by unique code
    /// </summary>
    Task<Report> GetByCodeAsync(string reportCode);
    
    /// <summary>
    /// Check if report code exists
    /// </summary>
    Task<bool> ExistsByCodeAsync(string reportCode);

    // ============================================================================
    // QUERY BY TYPE AND CATEGORY
    // ============================================================================
    
    /// <summary>
    /// Get reports by type
    /// </summary>
    Task<List<Report>> GetByTypeAsync(Enums.ReportType type, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports by category
    /// </summary>
    Task<List<Report>> GetByCategoryAsync(ReportCategory category, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports by type and category
    /// </summary>
    Task<List<Report>> GetByTypeAndCategoryAsync(Enums.ReportType type, ReportCategory category, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports by status
    /// </summary>
    Task<List<Report>> GetByStatusAsync(Enums.ReportStatus status, int pageNumber = 1, int pageSize = 20);

    // ============================================================================
    // QUERY BY TIME PERIOD
    // ============================================================================
    
    /// <summary>
    /// Get reports by reporting period
    /// </summary>
    Task<List<Report>> GetByReportingPeriodAsync(DateTime periodStart, DateTime periodEnd, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports generated within date range
    /// </summary>
    Task<List<Report>> GetByGenerationDateAsync(DateTime generatedStart, DateTime generatedEnd, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports for specific date
    /// </summary>
    Task<List<Report>> GetForDateAsync(DateTime date, int pageNumber = 1, int pageSize = 20);

    // ============================================================================
    // REGULATORY REPORTS
    // ============================================================================
    
    /// <summary>
    /// Get regulatory reports
    /// </summary>
    Task<List<Report>> GetRegulatoryReportsAsync(int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get regulatory reports by authority
    /// </summary>
    Task<List<Report>> GetRegulatoryReportsByAuthorityAsync(string regulatoryAuthority, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get pending regulatory submissions
    /// </summary>
    Task<List<Report>> GetPendingRegulatorySubmissionsAsync();
    
    /// <summary>
    /// Get overdue regulatory reports
    /// </summary>
    Task<List<Report>> GetOverdueRegulatoryReportsAsync(DateTime currentDate);
    
    /// <summary>
    /// Get regulatory reports due within days
    /// </summary>
    Task<List<Report>> GetRegulatoryReportsDueWithinAsync(int days, DateTime currentDate);

    // ============================================================================
    // QUERY BY USER
    // ============================================================================
    
    /// <summary>
    /// Get reports generated by user
    /// </summary>
    Task<List<Report>> GetByGeneratedByAsync(string userId, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports submitted by user
    /// </summary>
    Task<List<Report>> GetBySubmittedByAsync(string userId, int pageNumber = 1, int pageSize = 20);

    // ============================================================================
    // SEARCH AND FILTER
    // ============================================================================
    
    /// <summary>
    /// Search reports by name or code
    /// </summary>
    Task<List<Report>> SearchAsync(string searchTerm, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports with advanced filters
    /// </summary>
    Task<List<Report>> GetWithFiltersAsync(
        Enums.ReportType? type = null,
        ReportCategory? category = null,
        Enums.ReportStatus? status = null,
        bool? isRegulatory = null,
        DateTime? periodStart = null,
        DateTime? periodEnd = null,
        DateTime? generatedStart = null,
        DateTime? generatedEnd = null,
        string generatedBy = null,
        int pageNumber = 1,
        int pageSize = 20);

    // ============================================================================
    // STATISTICS AND ANALYTICS
    // ============================================================================
    
    /// <summary>
    /// Get report count by type
    /// </summary>
    Task<Dictionary<Enums.ReportType, int>> GetCountByTypeAsync();
    
    /// <summary>
    /// Get report count by category
    /// </summary>
    Task<Dictionary<ReportCategory, int>> GetCountByCategoryAsync();
    
    /// <summary>
    /// Get report count by status
    /// </summary>
    Task<Dictionary<Enums.ReportStatus, int>> GetCountByStatusAsync();
    
    /// <summary>
    /// Get report generation statistics for period
    /// </summary>
    Task<Dictionary<string, object>> GetGenerationStatisticsAsync(DateTime periodStart, DateTime periodEnd);
    
    /// <summary>
    /// Get regulatory compliance statistics
    /// </summary>
    Task<Dictionary<string, object>> GetRegulatoryComplianceStatisticsAsync();

    // ============================================================================
    // ARCHIVAL AND CLEANUP
    // ============================================================================
    
    /// <summary>
    /// Get reports eligible for archival
    /// </summary>
    Task<List<Report>> GetEligibleForArchivalAsync(DateTime cutoffDate);
    
    /// <summary>
    /// Get archived reports
    /// </summary>
    Task<List<Report>> GetArchivedReportsAsync(int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports by archive location
    /// </summary>
    Task<List<Report>> GetByArchiveLocationAsync(string archiveLocation);

    // ============================================================================
    // PERFORMANCE AND MONITORING
    // ============================================================================
    
    /// <summary>
    /// Get failed reports
    /// </summary>
    Task<List<Report>> GetFailedReportsAsync(int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get reports by file size range
    /// </summary>
    Task<List<Report>> GetByFileSizeRangeAsync(long minSize, long maxSize, int pageNumber = 1, int pageSize = 20);
    
    /// <summary>
    /// Get largest reports
    /// </summary>
    Task<List<Report>> GetLargestReportsAsync(int count = 10);
    
    /// <summary>
    /// Get report generation performance metrics
    /// </summary>
    Task<Dictionary<string, object>> GetPerformanceMetricsAsync(DateTime periodStart, DateTime periodEnd);

    // ============================================================================
    // BULK OPERATIONS
    // ============================================================================
    
    /// <summary>
    /// Bulk update report status
    /// </summary>
    Task BulkUpdateStatusAsync(List<Guid> reportIds, Enums.ReportStatus newStatus);
    
    /// <summary>
    /// Bulk archive reports
    /// </summary>
    Task BulkArchiveAsync(List<Guid> reportIds, string archiveLocation);
    
    /// <summary>
    /// Delete old reports (hard delete for cleanup)
    /// </summary>
    Task DeleteOldReportsAsync(DateTime cutoffDate);

    // ============================================================================
    // VALIDATION AND INTEGRITY
    // ============================================================================
    
    /// <summary>
    /// Validate report data integrity
    /// </summary>
    Task<List<string>> ValidateDataIntegrityAsync(Guid reportId);
    
    /// <summary>
    /// Check for duplicate reports
    /// </summary>
    Task<List<Report>> FindDuplicateReportsAsync(string reportCode, DateTime periodStart, DateTime periodEnd);
    
    /// <summary>
    /// Get reports missing required data
    /// </summary>
    Task<List<Report>> GetReportsWithMissingDataAsync();

    // ============================================================================
    // CUSTOM QUERIES
    // ============================================================================
    
    /// <summary>
    /// Execute custom query with parameters
    /// </summary>
    Task<List<Report>> ExecuteCustomQueryAsync(string query, Dictionary<string, object> parameters);
    
    /// <summary>
    /// Get report summary data
    /// </summary>
    Task<Dictionary<string, object>> GetReportSummaryAsync(Guid reportId);
    
    /// <summary>
    /// Get reports requiring regeneration
    /// </summary>
    Task<List<Report>> GetReportsRequiringRegenerationAsync(DateTime currentDate, int maxAgeInDays = 7);
}