// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wekeza.MVP4._0.Data;

#nullable disable

namespace Wekeza.MVP4._0.Migrations
{
    [DbContext(typeof(MVP4DbContext))]
    [Migration("20260123164336_AddBranchManagerModels")]
    partial class AddBranchManagerModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c99f5249-d3da-4c27-95c8-30df9f8559d8"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 29, 367, DateTimeKind.Utc).AddTicks(199),
                            Email = "admin@wekeza.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$N4S.3gzkdjm.gbDZRilLDeouiytDNRpYLpYa4YpeF4ltDHOpkpnv2",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("94aa038e-2d46-4213-bfec-eeae1e9921e3"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 30, 641, DateTimeKind.Utc).AddTicks(7796),
                            Email = "teller1@wekeza.com",
                            FullName = "John Teller",
                            IsActive = true,
                            PasswordHash = "$2a$11$Oc8kxnexAW4rRmS/AwkOS.wwwL/HSimZbkDim63Zq5UfevVq/3aD2",
                            Role = "Teller",
                            Username = "teller1"
                        },
                        new
                        {
                            Id = new Guid("df9f9316-3300-4ba5-855e-29ec444b0acc"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 30, 823, DateTimeKind.Utc).AddTicks(269),
                            Email = "supervisor1@wekeza.com",
                            FullName = "Jane Supervisor",
                            IsActive = true,
                            PasswordHash = "$2a$11$NpLfNUqSAZOz1prdkjIk/.EOnQvLrN1Orv75GNvbJjYuP/Wo8/YAW",
                            Role = "Supervisor",
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = new Guid("30a97946-9e11-462d-b4a7-0fbeb014267e"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 30, 984, DateTimeKind.Utc).AddTicks(1925),
                            Email = "branchmanager1@wekeza.com",
                            FullName = "Michael Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$9515R5dh5PU067BrT02NiulLWPYVI0XsEpwybSnWwOlXHisKcx.zq",
                            Role = "BranchManager",
                            Username = "branchmanager1"
                        },
                        new
                        {
                            Id = new Guid("f17ec715-1b1a-4810-95ff-869cf69717d4"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 31, 820, DateTimeKind.Utc).AddTicks(1506),
                            Email = "cashofficer1@wekeza.com",
                            FullName = "Sarah Cash",
                            IsActive = true,
                            PasswordHash = "$2a$11$tRGlEtF3xqThFTRqf/FiJOrvEMhzltPA20MyTF9KBRcXPYqJWYCRi",
                            Role = "CashOfficer",
                            Username = "cashofficer1"
                        },
                        new
                        {
                            Id = new Guid("1cb2eee2-859b-4d6a-b79e-0d29552bd021"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 32, 250, DateTimeKind.Utc).AddTicks(4754),
                            Email = "backoffice1@wekeza.com",
                            FullName = "David BackOffice",
                            IsActive = true,
                            PasswordHash = "$2a$11$Ea0eeSpeRW6NGOg134oc1OOb/H6wj7wckcgWpe3GaIip5sALE8k42",
                            Role = "BackOfficeStaff",
                            Username = "backoffice1"
                        },
                        new
                        {
                            Id = new Guid("b493e78c-acbd-48d4-a3ef-166747e2b6d7"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 32, 500, DateTimeKind.Utc).AddTicks(989),
                            Email = "customercare1@wekeza.com",
                            FullName = "Emily Care",
                            IsActive = true,
                            PasswordHash = "$2a$11$E2CbEfjuYv64kzmbi3x2LOornEKrK.AZRMYObrBc7SChkS8mCEwzu",
                            Role = "CustomerCareOfficer",
                            Username = "customercare1"
                        },
                        new
                        {
                            Id = new Guid("fb58333f-be86-4452-a9df-66abc4bf9d77"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 32, 687, DateTimeKind.Utc).AddTicks(6826),
                            Email = "bancassurance1@wekeza.com",
                            FullName = "Robert Insurance",
                            IsActive = true,
                            PasswordHash = "$2a$11$fpqxF7iO3MyFX/SJzrhmAeHgF3iEL7v4fYhfZ8bglhzG2azevsRT.",
                            Role = "BancassuranceAgent",
                            Username = "bancassurance1"
                        },
                        new
                        {
                            Id = new Guid("0fa71a27-3805-4e49-b0af-3c17b08a6a50"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 32, 852, DateTimeKind.Utc).AddTicks(8191),
                            Email = "compliance1@wekeza.com",
                            FullName = "Linda Compliance",
                            IsActive = true,
                            PasswordHash = "$2a$11$4Jsur8Iyh46BJPrhrc31BOKlziV4DtDNM.M6UBiBvzo3LaFgBIrHK",
                            Role = "ComplianceOfficer",
                            Username = "compliance1"
                        },
                        new
                        {
                            Id = new Guid("a9177969-5cb4-43d7-a269-c69b88496f22"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 33, 11, DateTimeKind.Utc).AddTicks(4211),
                            Email = "risk1@wekeza.com",
                            FullName = "James Risk",
                            IsActive = true,
                            PasswordHash = "$2a$11$C8URQbn9.WknJCGALhrG6OY5WV3lRT5R1WyLG.ZZKT8SQ2hPuOZ6u",
                            Role = "RiskOfficer",
                            Username = "risk1"
                        },
                        new
                        {
                            Id = new Guid("f3b81372-3dfa-45a9-a670-845fa1551ee2"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 33, 383, DateTimeKind.Utc).AddTicks(7716),
                            Email = "loanofficer1@wekeza.com",
                            FullName = "Patricia Loan",
                            IsActive = true,
                            PasswordHash = "$2a$11$XCcati.jZZo.KgDonprC1utrgbeHE6gmkP2kQfpdwsQfX25WZTXVu",
                            Role = "LoanOfficer",
                            Username = "loanofficer1"
                        },
                        new
                        {
                            Id = new Guid("13d46e19-b0f8-4b2e-a743-26475f432caf"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 33, 627, DateTimeKind.Utc).AddTicks(3719),
                            Email = "auditor1@wekeza.com",
                            FullName = "William Auditor",
                            IsActive = true,
                            PasswordHash = "$2a$11$HY9KjHFnpKe92XM6LLXunOLh1RLkJUwzQL3dsKLSMEByZNlzpveUa",
                            Role = "Auditor",
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = new Guid("0ea90821-b397-4a35-8f8b-7a272dfa1e63"),
                            CreatedAt = new DateTime(2026, 1, 23, 16, 43, 33, 961, DateTimeKind.Utc).AddTicks(5135),
                            Email = "itadmin1@wekeza.com",
                            FullName = "Thomas IT",
                            IsActive = true,
                            PasswordHash = "$2a$11$/ljmO6j2oPVimHrmHyLlT.i7ZoKdVJguw93o/BVjUVq8KBOxHCi/q",
                            Role = "ITAdministrator",
                            Username = "itadmin1"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TellerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BranchReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BranchReports");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CashPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ATMCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TellerCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VaultCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CashPositions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("RiskAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
