// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wekeza.MVP4._0.Data;

#nullable disable

namespace Wekeza.MVP4._0.Migrations
{
    [DbContext(typeof(MVP4DbContext))]
    [Migration("20260122205721_AddBranchManagerTables")]
    partial class AddBranchManagerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f1951ce-6e32-4d14-be17-f19c9d7003f8"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 13, 81, DateTimeKind.Utc).AddTicks(3589),
                            Email = "admin@wekeza.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$QmXFdmPc0JjB.ejq2WuTYOJXFxkSuktNsv0XRytSt.XWY0O18mL3W",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c6a1a5ab-756a-4f1a-8070-9182210dff84"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 13, 626, DateTimeKind.Utc).AddTicks(940),
                            Email = "teller1@wekeza.com",
                            FullName = "John Teller",
                            IsActive = true,
                            PasswordHash = "$2a$11$9kDsE1OOlsNE.aSBBar1ceHq6N/Hl0qltrwNkEF6RM5rQw67LOjc2",
                            Role = "Teller",
                            Username = "teller1"
                        },
                        new
                        {
                            Id = new Guid("432fec2e-84c8-4b17-b53c-08807783892d"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 14, 75, DateTimeKind.Utc).AddTicks(3617),
                            Email = "supervisor1@wekeza.com",
                            FullName = "Jane Supervisor",
                            IsActive = true,
                            PasswordHash = "$2a$11$O2QS42jZzJgjpjs9eDtoKubXWHXv9lnltPJDQwnWMGXS6yO1ExtnC",
                            Role = "Supervisor",
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = new Guid("0e762cd9-342c-4619-839a-d7afde1aad37"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 14, 440, DateTimeKind.Utc).AddTicks(9201),
                            Email = "branchmanager1@wekeza.com",
                            FullName = "Michael Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$6rtF8dCFIAHSC5eQ0qjoxuZYgmXtL4EClV0COWH0VGu4RGC9zPDSq",
                            Role = "BranchManager",
                            Username = "branchmanager1"
                        },
                        new
                        {
                            Id = new Guid("ebcab2f2-1e93-4c0b-9e21-70158c6ccc26"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 14, 910, DateTimeKind.Utc).AddTicks(4565),
                            Email = "cashofficer1@wekeza.com",
                            FullName = "Sarah Cash",
                            IsActive = true,
                            PasswordHash = "$2a$11$PfR0gfKD5wAbUfX/EH0kI.FWbTyunxMeYAaT8TXl6EFlvPRuTYSI6",
                            Role = "CashOfficer",
                            Username = "cashofficer1"
                        },
                        new
                        {
                            Id = new Guid("c8698b89-4851-4309-b425-e16382bd2114"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 15, 177, DateTimeKind.Utc).AddTicks(6305),
                            Email = "backoffice1@wekeza.com",
                            FullName = "David BackOffice",
                            IsActive = true,
                            PasswordHash = "$2a$11$PG1yyMKSkHgNNBvZ.5cR4OWETI/4TEaMYyQOndzjeU3Ed7zPo6ls.",
                            Role = "BackOfficeStaff",
                            Username = "backoffice1"
                        },
                        new
                        {
                            Id = new Guid("c21c2f13-4012-4a0b-a7e6-0f7cf919bcdc"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 15, 501, DateTimeKind.Utc).AddTicks(7324),
                            Email = "customercare1@wekeza.com",
                            FullName = "Emily Care",
                            IsActive = true,
                            PasswordHash = "$2a$11$RG8TDprLFn7gYkk8.OjKw.7v/c1LrHbXjgKkEhBpRZtiql58tElMi",
                            Role = "CustomerCareOfficer",
                            Username = "customercare1"
                        },
                        new
                        {
                            Id = new Guid("db7ca284-5c19-4fb7-8697-315296830690"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 15, 911, DateTimeKind.Utc).AddTicks(4191),
                            Email = "bancassurance1@wekeza.com",
                            FullName = "Robert Insurance",
                            IsActive = true,
                            PasswordHash = "$2a$11$3zGqZgvHF.NwKPDjYf/y5OLMKoo9rSh8ueaVyL.uSatwnR7wrrsCu",
                            Role = "BancassuranceAgent",
                            Username = "bancassurance1"
                        },
                        new
                        {
                            Id = new Guid("f536035d-a603-4f2f-8140-f64cf7599396"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 16, 589, DateTimeKind.Utc).AddTicks(8622),
                            Email = "compliance1@wekeza.com",
                            FullName = "Linda Compliance",
                            IsActive = true,
                            PasswordHash = "$2a$11$TCiKdHuwRNpW/d3FikLN/edi2mtXjcEV4NB0.mmuvICozFBPJKYSS",
                            Role = "ComplianceOfficer",
                            Username = "compliance1"
                        },
                        new
                        {
                            Id = new Guid("5628d9b4-f7a5-4084-9105-75ca2a89b4ff"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 17, 630, DateTimeKind.Utc).AddTicks(4202),
                            Email = "risk1@wekeza.com",
                            FullName = "James Risk",
                            IsActive = true,
                            PasswordHash = "$2a$11$gIHjToCnqQbIiD3ow5NH9.xMrKYybH9Al5TtagxCwWUzzSlFFoT7m",
                            Role = "RiskOfficer",
                            Username = "risk1"
                        },
                        new
                        {
                            Id = new Guid("32668084-5dfd-4e94-9421-0e78a226e2ca"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 17, 920, DateTimeKind.Utc).AddTicks(825),
                            Email = "loanofficer1@wekeza.com",
                            FullName = "Patricia Loan",
                            IsActive = true,
                            PasswordHash = "$2a$11$OCWLlHvpwGu3Hhp4eO72uei8aPGnkaLfdV3598Dg8MJft2apavCo6",
                            Role = "LoanOfficer",
                            Username = "loanofficer1"
                        },
                        new
                        {
                            Id = new Guid("b126528b-2dcf-49bc-8bc8-ccffac650a12"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 18, 295, DateTimeKind.Utc).AddTicks(234),
                            Email = "auditor1@wekeza.com",
                            FullName = "William Auditor",
                            IsActive = true,
                            PasswordHash = "$2a$11$.KG2n78NWl5QHDqPhYO2Fuer59Nyx52jxdMzmOa4wsOan1iqk05fe",
                            Role = "Auditor",
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = new Guid("ad02b494-4ec5-4e14-8c82-43d2b1596da0"),
                            CreatedAt = new DateTime(2026, 1, 22, 20, 57, 18, 576, DateTimeKind.Utc).AddTicks(8681),
                            Email = "itadmin1@wekeza.com",
                            FullName = "Thomas IT",
                            IsActive = true,
                            PasswordHash = "$2a$11$ba.UQNvSs/8RquAdPJqPm.TAWilnLmksUTlC/4F91XuxC8sXeN4fu",
                            Role = "ITAdministrator",
                            Username = "itadmin1"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TellerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BranchReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BranchReports");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CashPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ATMCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TellerCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VaultCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CashPositions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("RiskAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
