// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wekeza.MVP4._0.Data;

#nullable disable

namespace Wekeza.MVP4._0.Migrations
{
    [DbContext(typeof(MVP4DbContext))]
    [Migration("20260123205321_AddCustomerCareEntities")]
    partial class AddCustomerCareEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDormant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.AccountStatusRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("AccountStatusRequests");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b914b2c2-cad1-4358-af3b-12138789db32"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 16, 657, DateTimeKind.Utc).AddTicks(7018),
                            Email = "admin@wekeza.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$rt.yfTP8q7FBnp8oyO1yYemsrr85PxSmSsSn2TZOLnzV.GehtSnC6",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("5ba9885d-e5f2-4863-95d7-3d0c43624201"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 16, 877, DateTimeKind.Utc).AddTicks(8514),
                            Email = "teller1@wekeza.com",
                            FullName = "John Teller",
                            IsActive = true,
                            PasswordHash = "$2a$11$uitNd9F6R2EYmYkIX.bFY.a1bFcvh6hECzacIAvUav2PO0QzCbwxa",
                            Role = "Teller",
                            Username = "teller1"
                        },
                        new
                        {
                            Id = new Guid("1577a596-07ca-47a5-86b8-43c8394edad5"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 17, 64, DateTimeKind.Utc).AddTicks(9239),
                            Email = "supervisor1@wekeza.com",
                            FullName = "Jane Supervisor",
                            IsActive = true,
                            PasswordHash = "$2a$11$3nJrflLrFC5RH6p3yQ/vTO1oPEHX8xfA3tb0mBOMJAIfd980D8nzO",
                            Role = "Supervisor",
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = new Guid("b201979e-8265-4cb7-8d9a-e20ab4a23b9b"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 17, 276, DateTimeKind.Utc).AddTicks(6557),
                            Email = "branchmanager1@wekeza.com",
                            FullName = "Michael Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$pye5w4muIWZIZrjFdGjcnOkWqkCV6ASXBwKvL5sbtVaGZPDNurg3C",
                            Role = "BranchManager",
                            Username = "branchmanager1"
                        },
                        new
                        {
                            Id = new Guid("0b939281-1524-49ea-a1cc-6a4304d7f7c0"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 17, 460, DateTimeKind.Utc).AddTicks(1183),
                            Email = "cashofficer1@wekeza.com",
                            FullName = "Sarah Cash",
                            IsActive = true,
                            PasswordHash = "$2a$11$PpcBAtD4lpLPBoHYo1Bh4e5wv02Omnm5r6hsrfyCszSgQu1kw.Yey",
                            Role = "CashOfficer",
                            Username = "cashofficer1"
                        },
                        new
                        {
                            Id = new Guid("d87f87ca-6376-44cd-b41f-ff0bf4387c97"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 17, 695, DateTimeKind.Utc).AddTicks(7603),
                            Email = "backoffice1@wekeza.com",
                            FullName = "David BackOffice",
                            IsActive = true,
                            PasswordHash = "$2a$11$OHZIPsDopwbSMDswZ208K.rhUC9XdJaAhg3u7dqgDhAO9L2Q8bqc2",
                            Role = "BackOfficeStaff",
                            Username = "backoffice1"
                        },
                        new
                        {
                            Id = new Guid("59979aa7-3bc0-4aa3-b422-b7457f3cbd02"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 17, 930, DateTimeKind.Utc).AddTicks(9595),
                            Email = "customercare1@wekeza.com",
                            FullName = "Emily Care",
                            IsActive = true,
                            PasswordHash = "$2a$11$OsIKFsDBRy3yaAX7YkO7du.QsjVgnyLoLuG6hzapzlPtLQn1/4U9C",
                            Role = "CustomerCareOfficer",
                            Username = "customercare1"
                        },
                        new
                        {
                            Id = new Guid("81833d8a-258b-46ae-8fe4-c2bfb5fa503c"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 18, 163, DateTimeKind.Utc).AddTicks(3208),
                            Email = "bancassurance1@wekeza.com",
                            FullName = "Robert Insurance",
                            IsActive = true,
                            PasswordHash = "$2a$11$TNc3ApmE4ZcfSTv8QkHWFusNLONJQHKVVOqYs5JYIHsAGabsfMdI6",
                            Role = "BancassuranceAgent",
                            Username = "bancassurance1"
                        },
                        new
                        {
                            Id = new Guid("6ac4e0a1-a87e-44d5-9b5c-a1e5dece9fbb"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 18, 350, DateTimeKind.Utc).AddTicks(1772),
                            Email = "compliance1@wekeza.com",
                            FullName = "Linda Compliance",
                            IsActive = true,
                            PasswordHash = "$2a$11$/boLRhIC3fsGPMPEQZ2n3eTrgnesxZKbwksOfkJM9ZfIXvcfhH/4q",
                            Role = "ComplianceOfficer",
                            Username = "compliance1"
                        },
                        new
                        {
                            Id = new Guid("97fda817-e316-44ce-91b3-a02f2ca4f6f3"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 18, 530, DateTimeKind.Utc).AddTicks(5320),
                            Email = "risk1@wekeza.com",
                            FullName = "James Risk",
                            IsActive = true,
                            PasswordHash = "$2a$11$EowZEvLGrR6WXUxmlgJtc.sJEg/J5/R1UA2SMxlzOp8Rki7Zk/gHq",
                            Role = "RiskOfficer",
                            Username = "risk1"
                        },
                        new
                        {
                            Id = new Guid("8e21aab6-7803-4a33-a5d6-917b5b0e284f"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 18, 700, DateTimeKind.Utc).AddTicks(9807),
                            Email = "loanofficer1@wekeza.com",
                            FullName = "Patricia Loan",
                            IsActive = true,
                            PasswordHash = "$2a$11$FgalT2SSGD08Je51wY4Ucus4bsF4/yoo1YpdCY9M.JGu1DQ5zqspK",
                            Role = "LoanOfficer",
                            Username = "loanofficer1"
                        },
                        new
                        {
                            Id = new Guid("2e4d002b-e2a2-4dbd-9f6a-22b0409b01a8"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 18, 883, DateTimeKind.Utc).AddTicks(274),
                            Email = "auditor1@wekeza.com",
                            FullName = "William Auditor",
                            IsActive = true,
                            PasswordHash = "$2a$11$aj3PVxvfMzx52G/nvdjX0ObR2TjdIGYPayjWCaMjW3OI7G3pS6iRG",
                            Role = "Auditor",
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = new Guid("a901f763-e8ec-4f44-8084-6285b404170b"),
                            CreatedAt = new DateTime(2026, 1, 23, 20, 53, 19, 48, DateTimeKind.Utc).AddTicks(1587),
                            Email = "itadmin1@wekeza.com",
                            FullName = "Thomas IT",
                            IsActive = true,
                            PasswordHash = "$2a$11$FY2sBscQd.bD1J93v9QxkOvxH.R.6lX0LC8WTXG2bWkmlkFRac1Ka",
                            Role = "ITAdministrator",
                            Username = "itadmin1"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TellerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BranchReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BranchReports");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CardRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CardRequests");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CashPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ATMCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TellerCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VaultCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CashPositions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdateText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintUpdates");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("KycExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerComplaints");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("RiskAlerts");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.StandingInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FromAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InstructionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NextExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("StandingInstructions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.CustomerComplaint", "Complaint")
                        .WithMany("Documents")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintUpdate", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.CustomerComplaint", "Complaint")
                        .WithMany("Updates")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.StandingInstruction", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany("StandingInstructions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Transaction", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.Navigation("StandingInstructions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Complaints");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
