// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wekeza.MVP4._0.Data;

#nullable disable

namespace Wekeza.MVP4._0.Migrations
{
    [DbContext(typeof(MVP4DbContext))]
    [Migration("20260122171306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cde1a763-93a2-471f-94b4-d29aba96a2bf"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 4, 31, DateTimeKind.Utc).AddTicks(7232),
                            Email = "admin@wekeza.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$Wmv9267o7ZiiIxH8aPsKG.XTu/jttPheqj57XTZbrZRESoY398QFK",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("648471ac-7855-4359-93b8-76e343028b3e"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 4, 258, DateTimeKind.Utc).AddTicks(423),
                            Email = "teller1@wekeza.com",
                            FullName = "John Teller",
                            IsActive = true,
                            PasswordHash = "$2a$11$/EHeyE23ziD5D1jC0jFaouY7EUCaARPtd54ip8eaMp1X1RZ/5vPKG",
                            Role = "Teller",
                            Username = "teller1"
                        },
                        new
                        {
                            Id = new Guid("a1f46370-97af-4b3d-8e57-4c01b5b069ab"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 4, 480, DateTimeKind.Utc).AddTicks(1047),
                            Email = "supervisor1@wekeza.com",
                            FullName = "Jane Supervisor",
                            IsActive = true,
                            PasswordHash = "$2a$11$qfXv3hFWLfUyVl4HnBpyTecFDc9JAYANS6Xrk.EZ0r7aHFKcoZRmy",
                            Role = "Supervisor",
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = new Guid("86333acd-6b6e-414d-b6fe-6e6b7729c0dd"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 4, 656, DateTimeKind.Utc).AddTicks(8587),
                            Email = "branchmanager1@wekeza.com",
                            FullName = "Michael Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$G64bzyuDoV/5j.cI1YfYnOH/6N2TThgwldLMaKRrDPActXFbRz4sS",
                            Role = "BranchManager",
                            Username = "branchmanager1"
                        },
                        new
                        {
                            Id = new Guid("fb27197c-3c22-44ab-9bee-62c0ee7324f4"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 4, 831, DateTimeKind.Utc).AddTicks(5444),
                            Email = "cashofficer1@wekeza.com",
                            FullName = "Sarah Cash",
                            IsActive = true,
                            PasswordHash = "$2a$11$C6NBz3Wbhw3.SN1dpqRiUONbNdFQi4TA5DA034bwwPS9SnFlDxk6C",
                            Role = "CashOfficer",
                            Username = "cashofficer1"
                        },
                        new
                        {
                            Id = new Guid("49beb167-ab61-414a-9876-0e7497e1c476"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 7, DateTimeKind.Utc).AddTicks(3869),
                            Email = "backoffice1@wekeza.com",
                            FullName = "David BackOffice",
                            IsActive = true,
                            PasswordHash = "$2a$11$RoVTtXDb850n4nEG2ynpduCEbrsMxLAFhLpePXHgOg36MlhoBa72C",
                            Role = "BackOfficeStaff",
                            Username = "backoffice1"
                        },
                        new
                        {
                            Id = new Guid("21e4193f-9b28-4f36-bf8e-a2ed92fbd7a7"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 201, DateTimeKind.Utc).AddTicks(6359),
                            Email = "customercare1@wekeza.com",
                            FullName = "Emily Care",
                            IsActive = true,
                            PasswordHash = "$2a$11$IbAZFkYu7hSvLt/PVW8OTer3VUpPjWl0NWgTrcxwLFXoDQfevnN2y",
                            Role = "CustomerCareOfficer",
                            Username = "customercare1"
                        },
                        new
                        {
                            Id = new Guid("58eb5696-1895-4f7d-a029-66e64f086546"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 382, DateTimeKind.Utc).AddTicks(5406),
                            Email = "bancassurance1@wekeza.com",
                            FullName = "Robert Insurance",
                            IsActive = true,
                            PasswordHash = "$2a$11$/CArNoz2LiNQPzSWpgv.e.P8ZfkZKAoZ4FDjvLrf/o./DEo9JSgya",
                            Role = "BancassuranceAgent",
                            Username = "bancassurance1"
                        },
                        new
                        {
                            Id = new Guid("54102691-16fd-4760-afdc-c5fc079d03ea"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 577, DateTimeKind.Utc).AddTicks(9753),
                            Email = "compliance1@wekeza.com",
                            FullName = "Linda Compliance",
                            IsActive = true,
                            PasswordHash = "$2a$11$gvrjymwkyY8R7g7y3O2xUObFDYgWva3QyC8Q.tti2xQ1J3RwQzMUy",
                            Role = "ComplianceOfficer",
                            Username = "compliance1"
                        },
                        new
                        {
                            Id = new Guid("875825f3-4698-4058-85c9-60f1aab8de94"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 773, DateTimeKind.Utc).AddTicks(2273),
                            Email = "risk1@wekeza.com",
                            FullName = "James Risk",
                            IsActive = true,
                            PasswordHash = "$2a$11$rjfz3nfY82p05g.ebLGwi.BxsakwBb4osmS3X9D5aplcPHLMmCGKm",
                            Role = "RiskOfficer",
                            Username = "risk1"
                        },
                        new
                        {
                            Id = new Guid("f5d7f2e3-8f07-4ba3-983c-d7a87c1ca29e"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 5, 953, DateTimeKind.Utc).AddTicks(6118),
                            Email = "loanofficer1@wekeza.com",
                            FullName = "Patricia Loan",
                            IsActive = true,
                            PasswordHash = "$2a$11$MJ9EoY0nb7wN/oCU/bsjDeiTppS849j3kZlR55PvsGsBfQ/fBqIJO",
                            Role = "LoanOfficer",
                            Username = "loanofficer1"
                        },
                        new
                        {
                            Id = new Guid("a94edf1f-690a-4f6b-84f6-148ceb9e0d5e"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 6, 125, DateTimeKind.Utc).AddTicks(5393),
                            Email = "auditor1@wekeza.com",
                            FullName = "William Auditor",
                            IsActive = true,
                            PasswordHash = "$2a$11$W7MlVOo/He/RmC09/AGBCeNSveLNf270g6GaIYJ86/vieFLWSv5Te",
                            Role = "Auditor",
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = new Guid("d904aebf-52ce-45cc-9d12-82cdc39382ed"),
                            CreatedAt = new DateTime(2026, 1, 22, 17, 13, 6, 303, DateTimeKind.Utc).AddTicks(2635),
                            Email = "itadmin1@wekeza.com",
                            FullName = "Thomas IT",
                            IsActive = true,
                            PasswordHash = "$2a$11$Zca83ZFoTiKG2aiDue5rW.k1ZVrmNlQP0ft7qez7rFgAtZYbXf7am",
                            Role = "ITAdministrator",
                            Username = "itadmin1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
