// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wekeza.MVP4._0.Data;

#nullable disable

namespace Wekeza.MVP4._0.Migrations
{
    [DbContext(typeof(MVP4DbContext))]
    partial class MVP4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDormant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.AccountSignatory", b =>
                {
                    b.Property<Guid>("SignatoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SignatoryRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SignatoryRuleRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("SignatoryId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AddedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SignatoryRuleRuleId");

                    b.ToTable("AccountSignatories");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.AccountStatusRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("AccountStatusRequests");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("477b1c6b-3a4b-4643-9a82-cc9b2cc5d193"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 17, 538, DateTimeKind.Utc).AddTicks(9128),
                            Email = "admin@wekeza.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$2u7DpGjRz9M1e8CO/O1C/erwEypP9ItJ1upR9b.pPsNiPG9p.4LwS",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c7ee665d-68a4-42ed-a07b-767f216941f7"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 17, 704, DateTimeKind.Utc).AddTicks(6824),
                            Email = "teller1@wekeza.com",
                            FullName = "John Teller",
                            IsActive = true,
                            PasswordHash = "$2a$11$mWExedbQMk7FDCg10lwxT.N/R25FuMpUyNGQe600YQUQvw.Q.3qpu",
                            Role = "Teller",
                            Username = "teller1"
                        },
                        new
                        {
                            Id = new Guid("a31aadf3-40ea-46c2-aa50-c37e92ea7b8f"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 17, 854, DateTimeKind.Utc).AddTicks(3854),
                            Email = "supervisor1@wekeza.com",
                            FullName = "Jane Supervisor",
                            IsActive = true,
                            PasswordHash = "$2a$11$LXEeUjUBs/SE46G5VP0WC.LtIOHIobGVDrC1smachVTd.CWQYqY/e",
                            Role = "Supervisor",
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = new Guid("0100b114-c7ce-441a-b207-cb27cd964172"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 14, DateTimeKind.Utc).AddTicks(3662),
                            Email = "branchmanager1@wekeza.com",
                            FullName = "Michael Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$wt1KWdLy1ddiR2BgAIKAyeVff1.QpJ9NMZ7hDjB.QN6tq1ypKi3X2",
                            Role = "BranchManager",
                            Username = "branchmanager1"
                        },
                        new
                        {
                            Id = new Guid("c9ad1a65-d799-44a5-b700-f3f1b560ad46"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 180, DateTimeKind.Utc).AddTicks(8505),
                            Email = "cashofficer1@wekeza.com",
                            FullName = "Sarah Cash",
                            IsActive = true,
                            PasswordHash = "$2a$11$I7.FQFZhIoIn.t.1A5Uya.dvg5a/.GMx8J0vkUUQ1mhpTy.HIVlOO",
                            Role = "CashOfficer",
                            Username = "cashofficer1"
                        },
                        new
                        {
                            Id = new Guid("c3d53fde-7098-4c1b-9197-a33c7dca80cf"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 331, DateTimeKind.Utc).AddTicks(573),
                            Email = "backoffice1@wekeza.com",
                            FullName = "David BackOffice",
                            IsActive = true,
                            PasswordHash = "$2a$11$m8WKqtCDHEWa5KwWRZtshOFltxz8nhlN6V0KR8OTuc.uvrC0gZA52",
                            Role = "BackOfficeStaff",
                            Username = "backoffice1"
                        },
                        new
                        {
                            Id = new Guid("43f8750d-2ffd-4c3b-ade4-27670f1baf30"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 479, DateTimeKind.Utc).AddTicks(5931),
                            Email = "customercare1@wekeza.com",
                            FullName = "Emily Care",
                            IsActive = true,
                            PasswordHash = "$2a$11$1Nqzzm1QQrV2wgYAbY9P1ezer56gkvBvm/5Le8VSNxqGDPAdH5Gsu",
                            Role = "CustomerCareOfficer",
                            Username = "customercare1"
                        },
                        new
                        {
                            Id = new Guid("ba509ee4-aa92-4a7a-93f5-57c851b0b40a"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 629, DateTimeKind.Utc).AddTicks(5564),
                            Email = "bancassurance1@wekeza.com",
                            FullName = "Robert Insurance",
                            IsActive = true,
                            PasswordHash = "$2a$11$XLRZsCsNsCH7oDFrN2exOumMMv5jen59WuVBU1EgVl4TrnFS2VeNO",
                            Role = "BancassuranceAgent",
                            Username = "bancassurance1"
                        },
                        new
                        {
                            Id = new Guid("a6d5b107-4fbb-4d94-863c-c4f89befbbd0"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 788, DateTimeKind.Utc).AddTicks(6256),
                            Email = "compliance1@wekeza.com",
                            FullName = "Linda Compliance",
                            IsActive = true,
                            PasswordHash = "$2a$11$RaDaY0/RuhYdalz0ZfjB5unnvrJKwLJgK91sUUdCdmqiw/jo1.U1a",
                            Role = "ComplianceOfficer",
                            Username = "compliance1"
                        },
                        new
                        {
                            Id = new Guid("ea71b988-9d73-4282-a6a4-60c7e64fcf66"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 18, 935, DateTimeKind.Utc).AddTicks(9813),
                            Email = "risk1@wekeza.com",
                            FullName = "James Risk",
                            IsActive = true,
                            PasswordHash = "$2a$11$6J6LYGBack3GNAp5PnzEu.TTpD6RR0L1f9IsLVa/iB2SUenRlINki",
                            Role = "RiskOfficer",
                            Username = "risk1"
                        },
                        new
                        {
                            Id = new Guid("570fc979-c253-49c4-bf61-c19b629751f5"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 85, DateTimeKind.Utc).AddTicks(7657),
                            Email = "loanofficer1@wekeza.com",
                            FullName = "Patricia Loan",
                            IsActive = true,
                            PasswordHash = "$2a$11$VDZ2GcvOyWHh/rq716x7ve2koKa5mJ7a63UnJTi/aEgcYCL965f5.",
                            Role = "LoanOfficer",
                            Username = "loanofficer1"
                        },
                        new
                        {
                            Id = new Guid("c84f5c6a-908d-4acc-a976-9daedd65572a"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 233, DateTimeKind.Utc).AddTicks(8136),
                            Email = "auditor1@wekeza.com",
                            FullName = "William Auditor",
                            IsActive = true,
                            PasswordHash = "$2a$11$cA8wS.LpC.vuS1oncQzICuujTN5F.c3rwq.B3Fo/nOOcRtrjdCtDy",
                            Role = "Auditor",
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = new Guid("556a9a1c-a717-4a42-9148-694d97bc1c34"),
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 386, DateTimeKind.Utc).AddTicks(9706),
                            Email = "itadmin1@wekeza.com",
                            FullName = "Thomas IT",
                            IsActive = true,
                            PasswordHash = "$2a$11$X4fewXKRIL.EXnozAJ71HO5XlfM4qKgCTBBdA4DAfoYm0GGShKQDy",
                            Role = "ITAdministrator",
                            Username = "itadmin1"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApprovalStep", b =>
                {
                    b.Property<Guid>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("StepId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("WorkflowId");

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TellerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BankingAuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditId");

                    b.HasIndex("UserId");

                    b.ToTable("BankingAuditLogs");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BranchReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BranchReports");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CardRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CardRequests");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CashPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ATMCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TellerCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VaultCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CashPositions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ClaimDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Collateral", b =>
                {
                    b.Property<Guid>("CollateralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValuationReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CollateralId");

                    b.HasIndex("LoanId");

                    b.ToTable("Collaterals");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdateText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintUpdates");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CreditAssessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssessmentNotes")
                        .HasColumnType("text");

                    b.Property<decimal?>("CollateralValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DebtToIncomeRatio")
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskGrade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("AssessmentId");

                    b.HasIndex("AssessedBy");

                    b.HasIndex("LoanId");

                    b.ToTable("CreditAssessments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("KycExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerComplaints");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsuranceClaim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.HasIndex("ProcessedBy");

                    b.ToTable("InsuranceClaims");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsurancePolicy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BancassuranceOfficerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PremiumFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PolicyId");

                    b.HasIndex("BancassuranceOfficerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LinkedAccountId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.KYCData", b =>
                {
                    b.Property<Guid>("KYCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AMLFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("ComplianceNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RiskRating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("KYCId");

                    b.HasIndex("CustomerId");

                    b.ToTable("KYCData");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Loan", b =>
                {
                    b.Property<Guid>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DisbursementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LoanOfficerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tenure")
                        .HasColumnType("integer");

                    b.HasKey("LoanId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanNumber")
                        .IsUnique();

                    b.HasIndex("LoanOfficerId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.LoanDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("LoanId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("LoanDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.LoanRepayment", b =>
                {
                    b.Property<Guid>("RepaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ScheduledAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RepaymentId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanRepayments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("af59526f-9151-48ed-9bc7-e93451c07e33"),
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(745),
                            Resource = "Account"
                        },
                        new
                        {
                            PermissionId = new Guid("a4304a0e-ad64-45a7-b866-a8b23e34261f"),
                            Action = "Update",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(749),
                            Resource = "Account"
                        },
                        new
                        {
                            PermissionId = new Guid("87e95fae-804b-4d35-93df-f5110443fa89"),
                            Action = "Close",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(761),
                            Resource = "Account"
                        },
                        new
                        {
                            PermissionId = new Guid("f50053e5-04cd-43c6-8325-0134b61f90e2"),
                            Action = "Process",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(763),
                            Resource = "KYC"
                        },
                        new
                        {
                            PermissionId = new Guid("6faae9c1-4d37-4e9d-a1f5-d7f83b37f969"),
                            Action = "Process",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(765),
                            Resource = "Transaction"
                        },
                        new
                        {
                            PermissionId = new Guid("4dd32566-4c1c-4c95-af99-d1e72c135b32"),
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(767),
                            Resource = "Loan"
                        },
                        new
                        {
                            PermissionId = new Guid("6ea48b68-3085-479f-89d2-13eae2c95c1e"),
                            Action = "Assess",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(768),
                            Resource = "Loan"
                        },
                        new
                        {
                            PermissionId = new Guid("45f5c88e-f606-448a-b461-7fed7f7ad5e3"),
                            Action = "Disburse",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(770),
                            Resource = "Loan"
                        },
                        new
                        {
                            PermissionId = new Guid("8ea4e453-7873-4fcb-ac90-6f9f83f30c0b"),
                            Action = "Service",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(772),
                            Resource = "Loan"
                        },
                        new
                        {
                            PermissionId = new Guid("44e31322-8715-4eaf-b170-06f1f6ba2d98"),
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(774),
                            Resource = "Policy"
                        },
                        new
                        {
                            PermissionId = new Guid("31b3b817-03da-43ba-a3cf-3e5a9245442b"),
                            Action = "Service",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(777),
                            Resource = "Policy"
                        },
                        new
                        {
                            PermissionId = new Guid("14070ea3-b6a5-49bd-8d33-6747c5973191"),
                            Action = "Process",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(779),
                            Resource = "Claim"
                        },
                        new
                        {
                            PermissionId = new Guid("de2d627d-15eb-4308-b7c7-e520a5b44f47"),
                            Action = "Approve",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(780),
                            Resource = "All"
                        },
                        new
                        {
                            PermissionId = new Guid("07e1ecc8-7b1c-453b-bf7a-a7dd368efb77"),
                            Action = "Override",
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(782),
                            Resource = "Policy"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.PolicyBeneficiary", b =>
                {
                    b.Property<Guid>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("BenefitPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyBeneficiaries");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.PremiumPayment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScheduledAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PremiumPayments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("RiskAlerts");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskIndicator", b =>
                {
                    b.Property<Guid>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KYCId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IndicatorId");

                    b.HasIndex("IdentifiedBy");

                    b.HasIndex("KYCId");

                    b.ToTable("RiskIndicators");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ApprovalLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4e0a5944-984e-4a04-9809-d48c85a7c143"),
                            ApprovalLimit = 10000m,
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(557),
                            Description = "Handles account operations, KYC processing, and non-cash transactions",
                            IsActive = true,
                            RoleName = "BackOfficeOfficer"
                        },
                        new
                        {
                            RoleId = new Guid("2af2ad61-c154-4102-ac0f-beff8c18bbca"),
                            ApprovalLimit = 50000m,
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(595),
                            Description = "Manages complete credit lifecycle within approval limits",
                            IsActive = true,
                            RoleName = "LoanOfficer"
                        },
                        new
                        {
                            RoleId = new Guid("d7cffe60-ef05-4e91-9c87-52cce0ba42e0"),
                            ApprovalLimit = 25000m,
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(597),
                            Description = "Manages insurance products within banking system",
                            IsActive = true,
                            RoleName = "BancassuranceOfficer"
                        },
                        new
                        {
                            RoleId = new Guid("87d762f8-ef92-4636-96ec-a0150d9a20de"),
                            ApprovalLimit = 500000m,
                            CreatedAt = new DateTime(2026, 1, 24, 17, 58, 19, 387, DateTimeKind.Utc).AddTicks(599),
                            Description = "Approval authority for high-risk actions and policy overrides",
                            IsActive = true,
                            RoleName = "BranchManager"
                        });
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.SignatoryRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinimumSignatures")
                        .HasColumnType("integer");

                    b.Property<string>("SignatoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RuleId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("SignatoryRules");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.StandingInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FromAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InstructionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NextExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("StandingInstructions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.WorkflowInstance", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessJustification")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WorkflowId");

                    b.HasIndex("InitiatedBy");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.AccountSignatory", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.SignatoryRule", null)
                        .WithMany("AccountSignatories")
                        .HasForeignKey("SignatoryRuleRuleId");

                    b.Navigation("Account");

                    b.Navigation("AddedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ApprovalStep", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wekeza.MVP4._0.Models.WorkflowInstance", "Workflow")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.BankingAuditLog", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ClaimDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.InsuranceClaim", "Claim")
                        .WithMany("ClaimDocuments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Collateral", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Loan", "Loan")
                        .WithMany("Collaterals")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.CustomerComplaint", "Complaint")
                        .WithMany("Documents")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.ComplaintUpdate", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.CustomerComplaint", "Complaint")
                        .WithMany("Updates")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CreditAssessment", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "AssessedByUser")
                        .WithMany()
                        .HasForeignKey("AssessedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Loan", "Loan")
                        .WithMany("CreditAssessments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessedByUser");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsuranceClaim", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.InsurancePolicy", "Policy")
                        .WithMany("InsuranceClaims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Policy");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsurancePolicy", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "BancassuranceOfficer")
                        .WithMany()
                        .HasForeignKey("BancassuranceOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Account", "LinkedAccount")
                        .WithMany()
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BancassuranceOfficer");

                    b.Navigation("Customer");

                    b.Navigation("LinkedAccount");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.KYCData", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Loan", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wekeza.MVP4._0.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "LoanOfficer")
                        .WithMany()
                        .HasForeignKey("LoanOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Customer");

                    b.Navigation("LoanOfficer");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.LoanDocument", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Loan", "Loan")
                        .WithMany("LoanDocuments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.LoanRepayment", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Loan", "Loan")
                        .WithMany("LoanRepayments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.PolicyBeneficiary", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.InsurancePolicy", "Policy")
                        .WithMany("PolicyBeneficiaries")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.PremiumPayment", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.InsurancePolicy", "Policy")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Policy");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RiskIndicator", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "IdentifiedByUser")
                        .WithMany()
                        .HasForeignKey("IdentifiedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.KYCData", "KYCData")
                        .WithMany("RiskIndicators")
                        .HasForeignKey("KYCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentifiedByUser");

                    b.Navigation("KYCData");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.RolePermission", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.SignatoryRule", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.StandingInstruction", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany("StandingInstructions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Transaction", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.UserRoleAssignment", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.WorkflowInstance", b =>
                {
                    b.HasOne("Wekeza.MVP4._0.Models.ApplicationUser", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatedByUser");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Account", b =>
                {
                    b.Navigation("StandingInstructions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Complaints");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.CustomerComplaint", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsuranceClaim", b =>
                {
                    b.Navigation("ClaimDocuments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.InsurancePolicy", b =>
                {
                    b.Navigation("InsuranceClaims");

                    b.Navigation("PolicyBeneficiaries");

                    b.Navigation("PremiumPayments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.KYCData", b =>
                {
                    b.Navigation("RiskIndicators");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Loan", b =>
                {
                    b.Navigation("Collaterals");

                    b.Navigation("CreditAssessments");

                    b.Navigation("LoanDocuments");

                    b.Navigation("LoanRepayments");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.SignatoryRule", b =>
                {
                    b.Navigation("AccountSignatories");
                });

            modelBuilder.Entity("Wekeza.MVP4._0.Models.WorkflowInstance", b =>
                {
                    b.Navigation("ApprovalSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
